services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - ./app1/.env
    # volumes:
    #   - ./app1:/home/app
    environment:
      - DJANGO_SETTINGS_MODULE=webappexample.settings

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - ./app2/.env
    # volumes:
    #   - ./app2:/home/app
    environment:
      - DJANGO_SETTINGS_MODULE=webappexample.settings

  app3:
    build:
      context: ./app3
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    env_file:
      - ./app3/.env
    # volumes:
    #   - ./app3:/home/app
    environment:
      - DJANGO_SETTINGS_MODULE=webappexample.settings
