version: '3.8'

services:
  app1:
    build:
      context: ./App1
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./App1:/home/app
    environment:
      - DJANGO_SETTINGS_MODULE=App1.settings

  app2:
    build:
      context: ./App2
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./App2:/home/app
    environment:
      - DJANGO_SETTINGS_MODULE=App2.settings

  app3:
    build:
      context: ./App3
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    volumes:
      - ./App3:/home/app
    environment:
      - DJANGO_SETTINGS_MODULE=App3.settings
