# Utilisation de l'image Nginx pour servir des fichiers statiques
FROM nginx:alpine

# Copier les fichiers de l'application dans le répertoire de Nginx
COPY . /usr/share/nginx/html/

# Exposer le port 80 pour accéder à l'application
EXPOSE 80

